language: java
jdk:
  - openjdk6
  - oraclejdk7
  - openjdk7
before_install:
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r22.6.2-linux.tgz
  - tar xzf android-sdk_r22.6.2-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  - echo yes | android update sdk -t tools,platform-tools,android-19,build-tools-19.0.3 --force --no-ui
  # verify files exist in right paths
  - find $ANDROID_HOME/build-tools
after_success:
  - mvn clean cobertura:cobertura coveralls:cobertura
