language: android
android:
  components:
    - build-tools-19.0.3
    - android-19
    - sysimg-19
    - extra-android-support
  licenses:
    - android-sdk-license-bcbbd656
    - '.*intel.+'
before_install:
  - mkdir mvnDeployer
  - git clone git://github.com/mosabua/maven-android-sdk-deployer.git mvnDeployer/maven-android-sdk-deployer
  - cd mvnDeployer/maven-android-sdk-deployer/extras/compatibility-v4
  - mvn clean install
  - cd -
after_success:
  - mvn clean cobertura:cobertura coveralls:cobertura
